/**
 * @file main.c
 * @brief Pi Shield Hardware Entry Point (Node 1 - STM32C542CCT6).
 * Generated/Managed by STM32CubeMX. Hands over execution to app_main().
 */

#include "main.h"
#include "app.h"

/*
 * Peripheral initialisation entry points generated by STM32CubeMX alongside
 * this file. Declared non-static to match CubeMX output.
 *
 * These are NOT defined in this repository yet. Node 1 has no generated HAL
 * project (no Drivers/, hal_conf, startup assembly, or linker script), so the
 * definitions must arrive with that project. See docs/board_findings.md and
 * the node 1 CubeMX tracking issue.
 *
 * Core/Inc/main.h is currently a hand-written stub, not a CubeMX header, so
 * HAL_Init is declared here. Once the generated header exists this declaration
 * is redundant but harmless, and matches the prototype the HAL provides.
 */
void HAL_Init(void);
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_FDCAN1_Init(void);
void MX_I2C1_Init(void);

int main(void) {

    /* USER CODE BEGIN 2 */

    /* Hand over execution to Application Layer (Src/app.c).
     * CubeMX code generation preserves this call, while all
     * application logic, state machines, and telemetry stay safe in app.c */
    app_main();
    /* USER CODE END 2 */

    /* Infinite loop fallback */
    while (1) {
    }
}

void Error_Handler(void) {
    while (1) {
    }
}
