/**
 * @file main.c
 * @brief Power Slab Hardware Entry Point (Node 3 - STM32C542CCT6).
 * Generated/Managed by STM32CubeMX. Hands over execution to app_main().
 */

#include "main.h"
#include "app.h"

/*
 * Peripheral initialisation entry points generated by STM32CubeMX alongside
 * this file. Declared non-static to match CubeMX output.
 *
 * These are NOT defined in this repository yet. Node 3 has no generated HAL
 * project (no Drivers/, hal_conf, startup assembly, or linker script), so the
 * definitions must arrive with that project. See docs/board_findings.md and
 * the node 3 CubeMX tracking issue.
 *
 * Core/Inc/main.h is currently a hand-written stub, not a CubeMX header, so
 * HAL_Init is declared here. Once the generated header exists this declaration
 * is redundant but harmless, and matches the prototype the HAL provides.
 */
void HAL_Init(void);
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_FDCAN1_Init(void);
void MX_I2C1_Init(void);

int main(void) {

    /* Initialise the HAL runtime first: SysTick must be running before any
     * application code reads time_get_ms(), and the HAL state machine must be
     * reset before any peripheral handle is touched. */
    HAL_Init();

    /* Configure the PLL and flash latency before any peripheral is clocked. */
    SystemClock_Config();

    /* USER CODE BEGIN 2 */

    /* Peripheral init must complete before app_main() runs, because
     * node3_app_init() calls bsp_init() and can_init() and then immediately
     * starts the power sequencer and the INA237 rail monitor. */
    MX_GPIO_Init();
    MX_FDCAN1_Init();
    MX_I2C1_Init();

    /* Hand over execution to Application Layer (Src/app.c).
     * CubeMX code generation preserves this call, while all
     * application logic, state machines, and telemetry stay safe in app.c */
    app_main();
    /* USER CODE END 2 */

    /* Infinite loop fallback */
    while (1) {
    }
}

void Error_Handler(void) {
    while (1) {
    }
}
